name: Train dev/prod models

on:
  push:

jobs:
  dev-train:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job for dev env
      run: |
        az configure --defaults group=mlops-learn-rg
        az configure --defaults workspace=mlops-learn-ws
        az ml job create --file src/job.yml --stream

  prod-train:
    needs: dev-train
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job for prod env
      run: |
        az configure --defaults group=mlops-learn-rg
        az configure --defaults workspace=mlops-learn-ws
        az ml job create --file src/prod_job.yml --stream
